<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
	</PropertyGroup>
	<PropertyGroup>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<Version>1.0.4</Version>
		<Authors>Unknown</Authors>
		<Description>Flac (Free Lossless Audio Coded) support for NAudio.</Description>
		<PackageLicenseExpression>Unlicense</PackageLicenseExpression>
		<PackageProjectUrl>https://github.com/VPKSoft/NAudio.Flac</PackageProjectUrl>
		<RepositoryUrl>https://github.com/VPKSoft/NAudio.Flac</RepositoryUrl>
		<PackageIcon>Flac_logo.png</PackageIcon>
		<RepositoryType>git</RepositoryType>
		<PackageTags>music naudio flac</PackageTags>
		<PackageReleaseNotes>Just trying to keep this alive:, see: https://github.com/VPKSoft/NAudio.Flac</PackageReleaseNotes>
		<PackageId>NAudio.Flac.Unknown</PackageId>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="NAudio" Version="3.0.0-preview.18" />
	</ItemGroup>
	<ItemGroup>
		<None Include="..\Flac_logo.png">
			<Pack>True</Pack>
			<PackagePath></PackagePath>
		</None>
	</ItemGroup>

</Project>